export const data = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
  {
    id: "2",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
  {
    id: "3",
    name: "John Doe",
    email: "john.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
];

