export const data = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
  {
    id: "2",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
  {
    id: "3",
    name: "John Doe",
    email: "john.doe@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
    hindiMarks: 60,
    socialScienceMarks: 50,
  },
  {
    id: "4",
    name: "unnati bamani",
    email: "unnati.bamani@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
  },
  {
    id: "5",
    name: "Nitin Rangan",
    email: "nitin.rangan@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
  },
  {
    id: "6",
    name: "Abhishek",
    email: "abhishek@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
  },
  {
    id: "7",
    name: "Abhishek",
    email: "abhishek@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
    scienceMarks: 80,
    englishMarks: 70,
  },
  {
    id: "8",
    name: "Abhishek",
    email: "abhishek@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
  },
  {
    id: "9",
    name: "Abhishek",
    email: "abhishek@example.com",
    profileImage: "https://picsum.photos/200/300",
    class: "10th",
    section: "A",
    mathsMarks: 90,
  },
];

