export const hrData = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phoneNumber: "555-0101",
    department: "IT",
    position: "Software Engineer",
    salary: 75000,
    hireDate: "2021-06-15",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phoneNumber: "555-0102",
    department: "HR",
    position: "HR Manager",
    salary: 85000,
    hireDate: "2019-03-12",
  },
  {
    id: "3",
    name: "Alice Johnson",
    email: "alice.j@example.com",
    phoneNumber: "555-0103",
    department: "Marketing",
    position: "Marketing Specialist",
    salary: 60000,
    hireDate: "2022-08-01",
  },
  {
    id: "4",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    phoneNumber: "555-0104",
    department: "Finance",
    position: "CFO",
    salary: 120000,
    hireDate: "2015-11-30",
  },
  {
    id: "5",
    name: "Charlie White",
    email: "charlie.w@example.com",
    phoneNumber: "555-0105",
    department: "IT",
    position: "System Analyst",
    salary: 70000,
    hireDate: "2020-02-14",
  },
  {
    id: "6",
    name: "Diana Green",
    email: "diana.g@example.com",
    phoneNumber: "555-0106",
    department: "Sales",
    position: "Sales Executive",
    salary: 65000,
    hireDate: "2023-01-20",
  },
  {
    id: "7",
    name: "Edward Black",
    email: "edward.b@example.com",
    phoneNumber: "555-0107",
    department: "IT",
    position: "Project Manager",
    salary: 90000,
    hireDate: "2018-09-05",
  },
  {
    id: "8",
    name: "Fiona Blue",
    email: "fiona.b@example.com",
    phoneNumber: "555-0108",
    department: "HR",
    position: "Recruiter",
    salary: 60000,
    hireDate: "2020-07-11",
  },
  {
    id: "9",
    name: "George Red",
    email: "george.r@example.com",
    phoneNumber: "555-0109",
    department: "Operations",
    position: "Operations Manager",
    salary: 95000,
    hireDate: "2016-05-22",
  },
  {
    id: "10",
    name: "Hannah Purple",
    email: "hannah.p@example.com",
    phoneNumber: "555-0110",
    department: "Marketing",
    position: "Social Media Manager",
    salary: 55000,
    hireDate: "2022-10-18",
  },
  {
    id: "11",
    name: "Ian Orange",
    email: "ian.o@example.com",
    phoneNumber: "555-0111",
    department: "Finance",
    position: "Financial Analyst",
    salary: 80000,
    hireDate: "2017-04-15",
  },
  {
    id: "12",
    name: "Julia Gray",
    email: "julia.g@example.com",
    phoneNumber: "555-0112",
    department: "Sales",
    position: "Account Manager",
    salary: 70000,
    hireDate: "2021-12-01",
  },
  {
    id: "13",
    name: "Kevin Pink",
    email: "kevin.p@example.com",
    phoneNumber: "555-0113",
    department: "IT",
    position: "Junior Developer",
    salary: 60000,
    hireDate: "2023-03-15",
  },
  {
    id: "14",
    name: "Laura Cyan",
    email: "laura.c@example.com",
    phoneNumber: "555-0114",
    department: "Operations",
    position: "Supply Chain Lead",
    salary: 85000,
    hireDate: "2019-08-27",
  },
  {
    id: "15",
    name: "Mike Teal",
    email: "mike.t@example.com",
    phoneNumber: "555-0115",
    department: "Marketing",
    position: "Brand Manager",
    salary: 90000,
    hireDate: "2016-11-11",
  },
  {
    id: "16",
    name: "Nancy Violet",
    email: "nancy.v@example.com",
    phoneNumber: "555-0116",
    department: "HR",
    position: "HR Coordinator",
    salary: 55000,
    hireDate: "2022-05-30",
  },
  {
    id: "17",
    name: "Oscar Maroon",
    email: "oscar.m@example.com",
    phoneNumber: "555-0117",
    department: "IT",
    position: "DevOps Engineer",
    salary: 80000,
    hireDate: "2019-02-21",
  },
  {
    id: "18",
    name: "Paula Olive",
    email: "paula.o@example.com",
    phoneNumber: "555-0118",
    department: "Finance",
    position: "Accounting Manager",
    salary: 95000,
    hireDate: "2018-01-10",
  },
  {
    id: "19",
    name: "Quinn Indigo",
    email: "quinn.i@example.com",
    phoneNumber: "555-0119",
    department: "Sales",
    position: "Sales Manager",
    salary: 85000,
    hireDate: "2017-07-19",
  },
  {
    id: "20",
    name: "Ryan Gold",
    email: "ryan.g@example.com",
    phoneNumber: "555-0120",
    department: "Operations",
    position: "Warehouse Supervisor",
    salary: 60000,
    hireDate: "2023-06-25",
  },
];

