export const users = [
  {
    id: "1",
    name: "John Doe",
    class: "12C",
    mathsMarks: 68,
    scienceMarks: 49,
    englishMarks: 71,
  },
  {
    id: "2",
    name: "Jane Smith",
    class: "12C",
    mathsMarks: 82,
    scienceMarks: 92,
    englishMarks: 58,
  },
  {
    id: "3",
    name: "Alice Johnson",
    class: "11A",
    mathsMarks: 71,
    scienceMarks: 43,
    englishMarks: 81,
  },
  {
    id: "4",
    name: "Bob Brown",
    class: "12D",
    mathsMarks: 92,
    scienceMarks: 92,
    englishMarks: 83,
  },
  {
    id: "5",
    name: "Charlie White",
    class: "11B",
    mathsMarks: 51,
    scienceMarks: 65,
    englishMarks: 83,
  },
  {
    id: "6",
    name: "David Green",
    class: "10C",
    mathsMarks: 43,
    scienceMarks: 78,
    englishMarks: 61,
  },
  {
    id: "7",
    name: "Eve Black",
    class: "10A",
    mathsMarks: 95,
    scienceMarks: 98,
    englishMarks: 71,
  },
  {
    id: "8",
    name: "Frank Purple",
    class: "10B",
    mathsMarks: 68,
    scienceMarks: 68,
    englishMarks: 73,
  },
  {
    id: "9",
    name: "Grace Blue",
    class: "10B",
    mathsMarks: 71,
    scienceMarks: 67,
    englishMarks: 65,
  },
  {
    id: "10",
    name: "Henry Orange",
    class: "11B",
    mathsMarks: 90,
    scienceMarks: 58,
    englishMarks: 64,
  },
  {
    id: "11",
    name: "Ivy Yellow",
    class: "12A",
    mathsMarks: 88,
    scienceMarks: 94,
    englishMarks: 59,
  },
  {
    id: "12",
    name: "Jack Red",
    class: "12D",
    mathsMarks: 58,
    scienceMarks: 49,
    englishMarks: 84,
  },
  {
    id: "13",
    name: "Kara Pink",
    class: "12A",
    mathsMarks: 95,
    scienceMarks: 95,
    englishMarks: 91,
  },
  {
    id: "14",
    name: "Leo Gray",
    class: "12B",
    mathsMarks: 59,
    scienceMarks: 46,
    englishMarks: 95,
  },
  {
    id: "15",
    name: "Mona Cyan",
    class: "12C",
    mathsMarks: 77,
    scienceMarks: 93,
    englishMarks: 83,
  },
  {
    id: "16",
    name: "Nina Magenta",
    class: "10A",
    mathsMarks: 58,
    scienceMarks: 69,
    englishMarks: 42,
  },
  {
    id: "17",
    name: "Omar Violet",
    class: "10A",
    mathsMarks: 44,
    scienceMarks: 87,
    englishMarks: 76,
  },
  {
    id: "18",
    name: "Paul Indigo",
    class: "11A",
    mathsMarks: 87,
    scienceMarks: 64,
    englishMarks: 96,
  },
  {
    id: "19",
    name: "Quinn Lime",
    class: "12B",
    mathsMarks: 43,
    scienceMarks: 64,
    englishMarks: 100,
  },
  {
    id: "20",
    name: "Rita Gold",
    class: "12A",
    mathsMarks: 79,
    scienceMarks: 52,
    englishMarks: 95,
  },
];

